sudo: required
services:
    - docker

before_install:
    - docker build -t jy/drl -f Dockerfile.dev .
  
script : 
    - docker run -e CI=true jy/drl npm run test

deploy :
    provider : elasticbeanstalk
    region : "ap-southeast-1"
    app : "Hiep-Docker"
    env : "HiepDocker-env"
    bucket_name : "elasticbeanstalk-ap-southeast-1-121477722798"
    bucket_path : "Hiep-Docker"
    on:
        branch: master

    access_key_id : $ACCESS_KEY
    secret_access_key : $SECRET_KEY

language : generic